# Generated by Django 5.0 on 2025-11-02 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_delete_eventorganizer'),
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
