# Generated by Django 5.0 on 2025-11-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0004_alter_attendee_age_alter_attendee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
