# Generated by Django 5.0 on 2025-11-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_delete_eventorganizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
