# Generated by Django 5.0 on 2025-10-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventorganizer',
            old_name='contact_number',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
