# Generated by Django 5.0 on 2025-11-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_contact_number_eventorganizer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizer',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
