# Generated by Django 5.0 on 2025-11-03 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_capacity_event_ticket_url_event_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
    ]
