# Generated by Django 5.0 on 2025-11-04 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_image'),
        ('events', '0006_remove_event_category'),
    ]

    operations = [
    ]
