# Generated by Django 5.0 on 2025-11-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_add_created_updated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('tech', 'Tech'), ('art', 'Art'), ('food', 'Food'), ('charities', 'Charitable'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
